* Complete rewrite of sendADA.sh script to handle multiple UTx0 inputs, defrag and more. * env file updated with new protocol parameters and waitNewBlockCreated function, largely inspired from jormu-helper-scripts * balance.sh script added to get balance of address, sourced by sendADA.sh.

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -11,3 +11,26 @@ export NODE_SOCKET_PATH=$CNODE_HOME/sockets/node0.socket
 export CARDANO_NODE_SOCKET_PATH=$CNODE_HOME/sockets/node0.socket
 MAGIC=$(cat $GENESIS_JSON | jq -r .protocolMagicId)
 NWMAGIC=$(cat $GENESIS_JSON | jq -r .networkMagic)
+SLOT_DURATION=$(cat $GENESIS_JSON | jq -r .slotLength)
+TIMEOUT_NO_OF_BLOCKS=200
+
+getTip() {
+  echo $($CCLI shelley query tip --testnet-magic ${NWMAGIC} | sed -r 's/.*unBlockNo = ([0-9]+).*/\1/')
+}
+waitNewBlockCreated() {
+  COUNTER=${TIMEOUT_NO_OF_BLOCKS}
+  printf "\nWaiting for new block to be created (timeout = ${COUNTER} blocks = $((${COUNTER}*${SLOT_DURATION}))s)\n"
+  initialTip=$(getTip)
+  actualTip=${initialTip}
+
+  while [ "${actualTip}" = "${initialTip}" ]; do
+    sleep ${SLOT_DURATION}
+    actualTip=$(getTip)
+    COUNTER=$((COUNTER - ${SLOT_DURATION}))
+    if [ ${COUNTER} -lt 2 ]; then
+      printf "\n\n!!!!!! ERROR: Waited $((${TIMEOUT_NO_OF_BLOCKS} * ${SLOT_DURATION}))s secs (${TIMEOUT_NO_OF_BLOCKS}*${SLOT_DURATION}) and no new block created\n\n"
+      exit 1
+    fi
+  done
+  echo "New block was created - $(getTip)"
+}
