node 8.7.3
Breaking updates due to node 8.7.3 release.
Initial commit, untested and most likely incomplete. No docs update.

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -78,6 +78,7 @@
 #ASSET_POLICY_SK_FILENAME="policy.skey"
 #ASSET_POLICY_SCRIPT_FILENAME="policy.script"           # File extension '.script' mandatory
 #ASSET_POLICY_ID_FILENAME="policy.id"
+
 #CIP0094_POLL_URL="https://raw.githubusercontent.com/cardano-foundation/CIP-0094-polls/main/networks/polls.json" # URL for polls to vote against
 
 #MITHRIL_DOWNLOAD="N"                                  # (Y|N) Download latest Mithril snapshot
@@ -567,7 +568,7 @@ getNodeMetrics() {
     [[ ${node_metrics} =~ cardano_node_metrics_RTS_gcMajorNum_int[[:space:]]([^[:space:]]*) ]] && gc_major=${BASH_REMATCH[1]} || gc_major=0
     [[ ${node_metrics} =~ cardano_node_metrics_forks_int[[:space:]]([^[:space:]]*) ]] && forks=${BASH_REMATCH[1]} || forks=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_s[[:space:]]([^[:space:]]*) ]] && block_delay=${BASH_REMATCH[1]} || block_delay=0
-    [[ ${node_metrics} =~ cardano_node_metrics_served_block_count_int[[:space:]]([^[:space:]]*) ]] && blocks_served=${BASH_REMATCH[1]} || block_served=0
+    [[ ${node_metrics} =~ cardano_node_metrics_served_block_count_int[[:space:]]([^[:space:]]*) ]] && blocks_served=${BASH_REMATCH[1]} || blocks_served=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_lateblocks[[:space:]]([^[:space:]]*) ]] && blocks_late=${BASH_REMATCH[1]} || blocks_late=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_cdfOne[[:space:]]([^[:space:]]*) ]] && printf -v blocks_w1s "%.6f" ${BASH_REMATCH[1]} || blocks_w1s=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_cdfThree[[:space:]]([^[:space:]]*) ]] && printf -v blocks_w3s "%.6f" ${BASH_REMATCH[1]} || blocks_w3s=0
@@ -726,8 +727,8 @@ getPoolID() {
   pool_id_bech32=""
   pool_coldkey_vk_file="${pool_dir}/${POOL_COLDKEY_VK_FILENAME}"
   if [[ -f ${pool_coldkey_vk_file} ]]; then
-    println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file} --output-format hex"
-    println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file}"
+    [[ $(type -t println) = function ]] && println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file} --output-format hex"
+    [[ $(type -t println) = function ]] && println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file}"
     if ! pool_id=$(${CCLI} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" --output-format hex 2>/dev/null) || \
        ! pool_id_bech32=$(${CCLI} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" 2>/dev/null); then
       return 1
@@ -741,25 +742,16 @@ getPoolID() {
 
 # Description : Calculate expected interval between blocks
 slotInterval() {
-  if [[ -z ${DECENTRALISATION} || $(echo "${DECENTRALISATION} < 0.5" | bc) -eq 1 ]]; then d=0.5; else d=${DECENTRALISATION}; fi
-  echo "(${SLOT_LENGTH} / ${ACTIVE_SLOTS_COEFF} / ${d}) + 0.5" | bc -l | awk '{printf "%.0f\n", $1}'
+  echo "(${SLOT_LENGTH} / ${ACTIVE_SLOTS_COEFF}) + 0.5" | bc -l | awk '{printf "%.0f\n", $1}'
 }
 
-# Description : Identify current era and set variables accordingly
-# TODO: Track progress of https://github.com/intersectmbo/cardano-node/pull/4135 to see if era identifier can be removed in a future release. 
-getEraIdentifier() {
-  NETWORK_ERA=$(${CCLI} query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty')
-  case ${NETWORK_ERA} in
-    Byron)   ERA_IDENTIFIER="--byron-era" ;;
-    Shelley) ERA_IDENTIFIER="--shelley-era" ;;
-    Allegra) ERA_IDENTIFIER="--allegra-era" ;;
-    Mary)    ERA_IDENTIFIER="--mary-era" ;;
-    Alonzo)  ERA_IDENTIFIER="--alonzo-era" ;;
-    Babbage) ERA_IDENTIFIER="--babbage-era" ;;
-    *)       ERA_IDENTIFIER="--babbage-era"
-             [[ ${OFFLINE_MODE} = "N" ]] && return 1
-  esac
-  return 0
+getProtocolParams() {
+  PROT_PARAMS="$(${CCLI} query protocol-parameters ${NETWORK_IDENTIFIER} &>/dev/null)"
+  read -ra PROT_PARAMS_VERSION <<<"$(jq -r '[ .protocolVersion.major //0, .protocolVersion.minor //0]| @tsv' <<<"${PROT_PARAMS}" 2>/dev/null)"
+  PROT_MAJOR=${PROT_PARAMS_VERSION[0]}
+  PROT_MINOR=${PROT_PARAMS_VERSION[1]}
+  PROT_VERSION="${PROT_MAJOR}.${PROT_MINOR}"
+  [[ ${PROT_MAJOR} -eq 0 ]] && return 1 || return 0
 }
 
 telegramSend() {
@@ -1029,9 +1021,10 @@ if [[ -n "${CNODE_PID}" ]]; then
   fi
 fi
 
-node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "8.1.2" "${node_version}"; then
-  echo -e "\nKoios scripts has now been upgraded to support cardano-node 8.1.2 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version (eg: ./<script>.sh -b node-1.35.7 to switch scripts to an older branch).\n\n"
+node_version="$(${CNODEBIN} version | head -1 | cut -d' ' -f2)"
+cli_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
+if ! versionCheck "8.7.3" "${node_version}" || ! versionCheck "8.17.0.0" "${cli_version}"; then
+  echo -e "\nKoios scripts has now been upgraded to support cardano-node 8.7.3 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version (eg: ./<script>.sh -b node-8.1.2 to switch scripts to an older branch).\n\n"
   return 1
 fi
 
@@ -1079,6 +1072,9 @@ case ${NWMAGIC} in
     [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=0
 esac
 
+NETWORK_ERA=$(${CCLI} latest query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty' | tr '[:upper:]' '[:lower:]')
+[[ -z ${NETWORK_ERA} ]] && NETWORK_ERA=latest
+
 test_koios() {
   # make sure KOIOS_API is reachable, else fall back to cli
   [[ ${ENABLE_KOIOS} = 'Y' && -n ${KOIOS_API} && $(curl -sfk -o /dev/null -w "%{http_code}" -m 5 ${KOIOS_API}/tip | awk '{print $1}') = "200" ]] || unset KOIOS_API
@@ -1095,8 +1091,9 @@ if [[ ${OFFLINE_MODE} = "N" && ! -S ${CARDANO_NODE_SOCKET_PATH} ]]; then
   return 2
 fi
 
-if [[ ${OFFLINE_MODE} = "N" ]] && ! PROT_PARAMS="$(${CCLI} query protocol-parameters ${NETWORK_IDENTIFIER} 2>&1)"; then echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
-
-if ! DECENTRALISATION=$(jq -er .decentralization <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
+if [[ ${OFFLINE_MODE} = "N" ]] && ! getProtocolParams; then
+  echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}"
+  return 2
+fi
 
 return 0
