CNTools multisig (#1776)
## Description
Adds a couple of new larger features within CNTools:
- Multisig wallet support through advanced menu item.
- Custom mnemonic derivation path on mnemonic/hardware import and
creation of new mnemonic(seedphrase) generated wallet.
- New Vote menu option to hold everything related to voting on Cardano
incl Catalyst registration integration.

Task List:
- [x] Derive multisig keys according to CIP-1854 for mnemonic and
hardware wallets, or new cli keys
- [x] Create a multisig wallet specifying participants by wallet
selection or manual cred input.
    - [x] Time lock support using after directive.
- [x] Constructed using atLeast directive allowing any number of
signatures.
- [x] Wallet list/show extended to show additional details
- [x] normal wallets: key credentials (both multisig keys and regular
keys).
- [x] multisig wallets: script parsing to show participants, either
local wallets or external with credentials.
- [x] All transaction building code updated to handle payment and stake
scripts in addition to normal keys. If a multisig wallet is detected, an
offline transaction file is generated just like in hybrid mode.
- [x] Transaction >> Sign: updated to handle scripts in offline json tx
file.
- [x] Script validation logic to know if enough signatures have been
added before assembly.
- [x] Ability to create new mnemonic wallet (seedphrase).
- [x] Allows for custom account and index derivation for mnemonic and
hardware wallets.
- [x] Removed CIP95 SPO poll
- [x] New Catalyst registration option. 
    - [x] Prerequisites: 
- [x] cardano-signer created by @gitmachtl. Can be deployed using
`guild-deploy.sh -s x`.
- [x] catalyst-toolbox compiled from catalyst-core and hosted through
Koios share. Automatically downloaded within CNTools if needed.
    - [x] Uses CIP-36 style format with a single delegation
- [x] Vote keys not derived from 1694' derivation path but cli generated
for all types.
- [x] Ability to verify catalyst registration and check status, both own
and external vote pub keys.
- [x] New Catalyst QR option to display previously generated QR code
- [x] bump version
- [x] update changelog
- [x] tested and ready for alpha merge

---------

Co-authored-by: RdLrT <3169068+rdlrt@users.noreply.github.com>

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -50,17 +50,36 @@
 #WALLET_HW_PAY_SK_FILENAME="payment.hwsfile"
 #WALLET_PAY_ADDR_FILENAME="payment.addr"
 #WALLET_PAY_SCRIPT_FILENAME="payment.script"
-#WALLET_PAY_SCRIPT_ADDR_FILENAME="payment-script.addr"
 #WALLET_PAY_CRED_FILENAME="payment.cred"
+#WALLET_PAY_SCRIPT_CRED_FILENAME="payment.script.cred"
 #WALLET_BASE_ADDR_FILENAME="base.addr"
 #WALLET_STAKE_VK_FILENAME="stake.vkey"
 #WALLET_STAKE_SK_FILENAME="stake.skey"
 #WALLET_HW_STAKE_SK_FILENAME="stake.hwsfile"
 #WALLET_STAKE_ADDR_FILENAME="reward.addr"
+#WALLET_STAKE_SCRIPT_FILENAME="stake.script"
 #WALLET_STAKE_CRED_FILENAME="stake.cred"
+#WALLET_STAKE_SCRIPT_CRED_FILENAME="stake.script.cred"
 #WALLET_STAKE_CERT_FILENAME="stake.cert"
 #WALLET_STAKE_DEREG_FILENAME="stake.dereg"
 #WALLET_DELEGCERT_FILENAME="delegation.cert"
+#WALLET_VOTE_CATALYST_VK_FILENAME="vote-catalyst.vkey"
+#WALLET_VOTE_CATALYST_SK_FILENAME="vote-catalyst.skey"
+#WALLET_VOTE_CATALYST_QR_FILENAME="vote-catalyst-qrcode.png"
+#WALLET_GOV_DREP_VK_FILENAME="gov-drep.vkey"
+#WALLET_GOV_DREP_SK_FILENAME="gov-drep.skey"
+#WALLET_GOV_DREP_ID_FILENAME="gov-drep.id"
+#WALLET_GOV_DREP_CERT_FILENAME="gov-drep.cert"
+#WALLET_GOV_HW_DREP_SK_FILENAME="gov-drep.hwsfile"
+#WALLET_GOV_CC_HOT_VK_FILENAME="gov-cc-hot.vkey"
+#WALLET_GOV_CC_HOT_SK_FILENAME="gov-cc-hot.skey"
+#WALLET_GOV_HW_CC_HOT_SK_FILENAME="gov-cc-hot.hwsfile"
+#WALLET_GOV_CC_COLD_VK_FILENAME="gov-cc-cold.vkey"
+#WALLET_GOV_CC_COLD_SK_FILENAME="gov-cc-cold.skey"
+#WALLET_GOV_HW_CC_COLD_SK_FILENAME="gov-cc-cold.hwsfile"
+#WALLET_GOV_CC_HASH_FILENAME="gov-cc.hash"
+
+#WALLET_MULTISIG_PREFIX="ms_"                           # Filename for multisig files, uses separate keys derived using the 1854H paths
 
 #POOL_ID_FILENAME="pool.id"                             # Standardized names for all pool related files
 #POOL_HOTKEY_VK_FILENAME="hot.vkey"
@@ -255,6 +274,9 @@ cmdAvailable() {
   if ! command -v "$1" &>/dev/null; then
     printf "${FG_RED}ERROR${NC}: need '$1' (command not found)\nplease install with your packet manager of choice(apt/dnf etc..) and relaunch CNTools\nhttps://command-not-found.com/$1" 1>&2
     return 1
+  elif [[ ! -x $(command -v "$1") ]]; then
+    printf "${FG_RED}ERROR${NC}: '$1' missing executable permission, please fix" 1>&2
+    return 2
   fi
   return 0
 }
@@ -788,13 +810,15 @@ getProtocolParams() {
     fi
   fi
   # Set a collection of commonly used values
-  read -r PROT_MAJOR PROT_MINOR KEY_DEPOSIT POOL_DEPOSIT MIN_POOL_COST POOL_RETIRE_MAX_EPOCH <<<"$(jq -r '[
+  read -r PROT_MAJOR PROT_MINOR KEY_DEPOSIT POOL_DEPOSIT MIN_POOL_COST POOL_RETIRE_MAX_EPOCH DREP_DEPOSIT GOV_ACTION_DEPOSIT <<<"$(jq -r '[
   .protocolVersion.major //0,
   .protocolVersion.minor //0,
   .stakeAddressDeposit //0,
   .stakePoolDeposit //0,
   .minPoolCost //0,
-  .poolRetireMaxEpoch //0
+  .poolRetireMaxEpoch //0,
+  .dRepDeposit //0,
+  .govActionDeposit //0
   ] | @tsv' <<<"${PROT_PARAMS}" 2>/dev/null)"
   PROT_VERSION="${PROT_MAJOR}.${PROT_MINOR}"
   [[ ${PROT_MAJOR} -eq 0 ]] && return 1 || return 0
@@ -850,17 +874,35 @@ set_default_vars() {
   [[ -z ${WALLET_HW_PAY_SK_FILENAME} ]] && WALLET_HW_PAY_SK_FILENAME="payment.hwsfile"
   [[ -z ${WALLET_PAY_ADDR_FILENAME} ]] && WALLET_PAY_ADDR_FILENAME="payment.addr"
   [[ -z ${WALLET_PAY_SCRIPT_FILENAME} ]] && WALLET_PAY_SCRIPT_FILENAME="payment.script"
-  [[ -z ${WALLET_PAY_SCRIPT_ADDR_FILENAME} ]] && WALLET_PAY_SCRIPT_ADDR_FILENAME="payment-script.addr"
   [[ -z ${WALLET_PAY_CRED_FILENAME} ]] && WALLET_PAY_CRED_FILENAME="payment.cred"
+  [[ -z ${WALLET_PAY_SCRIPT_CRED_FILENAME} ]] && WALLET_PAY_SCRIPT_CRED_FILENAME="payment.script.cred"
   [[ -z ${WALLET_BASE_ADDR_FILENAME} ]] && WALLET_BASE_ADDR_FILENAME="base.addr"
   [[ -z ${WALLET_STAKE_VK_FILENAME} ]] && WALLET_STAKE_VK_FILENAME="stake.vkey"
   [[ -z ${WALLET_STAKE_SK_FILENAME} ]] && WALLET_STAKE_SK_FILENAME="stake.skey"
   [[ -z ${WALLET_HW_STAKE_SK_FILENAME} ]] && WALLET_HW_STAKE_SK_FILENAME="stake.hwsfile"
   [[ -z ${WALLET_STAKE_ADDR_FILENAME} ]] && WALLET_STAKE_ADDR_FILENAME="reward.addr"
+  [[ -z ${WALLET_STAKE_SCRIPT_FILENAME} ]] && WALLET_STAKE_SCRIPT_FILENAME="stake.script"
   [[ -z ${WALLET_STAKE_CRED_FILENAME} ]] && WALLET_STAKE_CRED_FILENAME="stake.cred"
+  [[ -z ${WALLET_STAKE_SCRIPT_CRED_FILENAME} ]] && WALLET_STAKE_SCRIPT_CRED_FILENAME="stake.script.cred"
   [[ -z ${WALLET_STAKE_CERT_FILENAME} ]] && WALLET_STAKE_CERT_FILENAME="stake.cert"
   [[ -z ${WALLET_STAKE_DEREG_FILENAME} ]] && WALLET_STAKE_DEREG_FILENAME="stake.dereg"
   [[ -z ${WALLET_DELEGCERT_FILENAME} ]] && WALLET_DELEGCERT_FILENAME="delegation.cert"
+  [[ -z ${WALLET_VOTE_CATALYST_VK_FILENAME} ]] && WALLET_VOTE_CATALYST_VK_FILENAME="vote-catalyst.vkey"
+  [[ -z ${WALLET_VOTE_CATALYST_SK_FILENAME} ]] && WALLET_VOTE_CATALYST_SK_FILENAME="vote-catalyst.skey"
+  [[ -z ${WALLET_VOTE_CATALYST_QR_FILENAME} ]] && WALLET_VOTE_CATALYST_QR_FILENAME="vote-catalyst-qrcode.png"
+  [[ -z ${WALLET_GOV_DREP_VK_FILENAME} ]] && WALLET_GOV_DREP_VK_FILENAME="gov-drep.vkey"
+  [[ -z ${WALLET_GOV_DREP_SK_FILENAME} ]] && WALLET_GOV_DREP_SK_FILENAME="gov-drep.skey"
+  [[ -z ${WALLET_GOV_DREP_ID_FILENAME} ]] && WALLET_GOV_DREP_ID_FILENAME="gov-drep.id"
+  [[ -z ${WALLET_GOV_DREP_CERT_FILENAME} ]] && WALLET_GOV_DREP_CERT_FILENAME="gov-drep.cert"
+  [[ -z ${WALLET_GOV_HW_DREP_SK_FILENAME} ]] && WALLET_GOV_HW_DREP_SK_FILENAME="gov-drep.hwsfile"
+  [[ -z ${WALLET_GOV_CC_HOT_VK_FILENAME} ]] && WALLET_GOV_CC_HOT_VK_FILENAME="gov-cc-hot.vkey"
+  [[ -z ${WALLET_GOV_CC_HOT_SK_FILENAME} ]] && WALLET_GOV_CC_HOT_SK_FILENAME="gov-cc-hot.skey"
+  [[ -z ${WALLET_GOV_HW_CC_HOT_SK_FILENAME} ]] && WALLET_GOV_HW_CC_HOT_SK_FILENAME="gov-cc-hot.hwsfile"
+  [[ -z ${WALLET_GOV_CC_COLD_VK_FILENAME} ]] && WALLET_GOV_CC_COLD_VK_FILENAME="gov-cc-cold.vkey"
+  [[ -z ${WALLET_GOV_CC_COLD_SK_FILENAME} ]] && WALLET_GOV_CC_COLD_SK_FILENAME="gov-cc-cold.skey"
+  [[ -z ${WALLET_GOV_HW_CC_COLD_SK_FILENAME} ]] && WALLET_GOV_HW_CC_COLD_SK_FILENAME="gov-cc-cold.hwsfile"
+  [[ -z ${WALLET_GOV_CC_HASH_FILENAME} ]] && WALLET_GOV_CC_HASH_FILENAME="gov-cc.hash"
+  [[ -z ${WALLET_MULTISIG_PREFIX} ]] && WALLET_MULTISIG_PREFIX="ms_"
   [[ -z ${POOL_ID_FILENAME} ]] && POOL_ID_FILENAME="pool.id"
   [[ -z ${POOL_HOTKEY_VK_FILENAME} ]] && POOL_HOTKEY_VK_FILENAME="hot.vkey"
   [[ -z ${POOL_HOTKEY_SK_FILENAME} ]] && POOL_HOTKEY_SK_FILENAME="hot.skey"
