Adapt for changes in cardano-node 1.26.x (#853)
* Adapt for changes in cardano-node 1.26.x
* Fix uptime counter
* Remove ERA_IDENTIFIER from scripts: query, startup (#858)
* Cleanup, remove unnecessary code
* Update check cleanup fix
* Update ledger-state schema
* 1.26.x writes ledger-state as a binary file instead of plain json. Switched to save ledger-state in variable instead of file on disk.
* Code adapted to handle the new ledger-state schema.
* Code adapted for changes in ledger-state dump used by 'Pool >> Show'
* gLiveView parsing and verification
* ss rtt parsing updated to use bash regex match instead.
* verification added to only accept numbers in result in case of missmatch in parsing.
* code cleanup
* Backup & restore - Exclude gpg encrypted keys from online backup and suppression of false alarms
* Bump cncli required version to 1.5.1

Co-authored-by: Priyank <3169068+rdlrt@users.noreply.github.com>

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -322,8 +322,8 @@ if ! mkdir -p "${TMP_DIR}" 2>/dev/null; then echo "ERROR: Failed to create direc
 [[ -z ${ASSET_POLICY_ID_FILENAME} ]] && ASSET_POLICY_ID_FILENAME="policy.id"
 
 node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "1.25.1" "${node_version}"; then
-  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.25.1 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
+if ! versionCheck "1.26.0" "${node_version}"; then
+  echo -e "\nGuild scripts has now been upgraded to support cardano-node 1.26.0 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version.\n\n"
   return 1
 fi
 
@@ -591,9 +591,8 @@ if [[ ${OFFLINE_MODE} = "N" && ! -S ${CARDANO_NODE_SOCKET_PATH} ]]; then
   return 2
 fi
 
-if ! getEraIdentifier; then echo "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
+if ! PROT_PARAMS="$(${CCLI} query protocol-parameters ${NETWORK_IDENTIFIER} 2>&1)"; then echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
 
-PROT_PARAMS="$(${CCLI} query protocol-parameters ${ERA_IDENTIFIER} ${NETWORK_IDENTIFIER} 2>&1)"
-if [[ -n "${PROT_PARAMS}" ]] && ! DECENTRALISATION=$(jq -er .decentralisationParam <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
+if ! DECENTRALISATION=$(jq -er .decentralization <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
 
 return 0
