Env patch (#514)
* Make default env paths customisable, allow automatic detection of vars where possible - similar to gLiveView

* Update gitignore to ignore swap and bkp files

* Add dialog to prereqs, backup env before downloading new one

* Shellcheck for env

* grab genesis files from config + cleanup

* More common variables added

* Shelley/Byron genesis parameters used by many scripts

* Query node for updated protocol parameters and save to PROT_PARAMS

* Add CNODE_PID

* Color coding variables

* G live view add total peers (#511)

* gLiveView 1.7 & env update

* PROT_PARAMS change

* include error output in variable (for use in CNTools when adapting updated env)

* .decentralisationParam jq validation also improved to be sure its able to grab value correctly

* Fix order of PROT_PARAMS

* env changes to save custom env config and option to force full update

- prereqs.sh > save custom env config changes on upgrade
- prereqs.sh > add full upgrade option to env, gLiveView and cnode.sh
- cnode.sh   > use config parameters from env instead of static paths if set
- env        > return with non-zero exit code instead of exit and let each script sourcing env handle exit.

* replace '#force update=true' with prereqs.sh -f flag to force update

* return 0 in env on success and make CNODE_PID a non failure check

* move node rev to main loop

* if cardano-node is upgraded and restarted while gLiveView is running in the background node rev was not updated.

* CNODE_PORT set by default in env file

* Merge #513 from @cloudstake

* verify in gLiveView that a compatible version of env file is used

Co-authored-by: Ola <ola.ahlman@gmail.com>
Co-authored-by: Damjan Ostrelič <damjan.ostrelic@gmail.com>

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -1,5 +1,25 @@
 #!/usr/bin/env bash
-# shellcheck disable=SC2034,SC2086,SC2230
+# shellcheck disable=SC2034,SC2086,SC2230,SC2009,SC2206
+
+######################################
+# User Variables - Change as desired #
+# Leave as is if unsure              #
+######################################
+
+#CCLI="${HOME}/.cabal/bin/cardano-cli"                  # Override automatic detection of path to cardano-cli executable
+#CNODE_HOME="/opt/cardano/cnode"                        # Override default CNODE_HOME path (defaults to /opt/cardano/cnode)
+CNODE_PORT=6000                                         # Set node port
+#CONFIG="${CNODE_HOME}/files/config.json"               # Override automatic detection of node config path
+#TOPOLOGY="${CNODE_HOME}/files/topology.json"           # Override automatic detection of node topology path
+#SOCKET="${CNODE_HOME}/sockets/node0.socket"            # Override automatic detection of path to socket
+EKG_HOST=127.0.0.1                                      # Set node EKG host
+#EKG_PORT=12788                                         # Override automatic detection of node EKG port
+#BLOCK_LOG_DIR="${CNODE_HOME}/db/blocks"                # CNTools Block Collector block dir set in cntools.config, override path if enabled and using non standard path
+
+######################################
+# Do NOT modify code below           #
+######################################
+
 CCLI=$(command -v cardano-cli)
 if [[ -z "${CCLI}" ]]; then
   if [[ -f "${HOME}/.cabal/bin/cardano-cli" ]]; then
@@ -8,18 +28,126 @@ if [[ -z "${CCLI}" ]]; then
     CCLI=$(command -v cardano-cli)
   else
     echo "You do not have a cardano-cli binary available in \$PATH. Please make it available before using CNTools. Refer to guild-operators documentation for the same."
-    exit 1
+    return 1
   fi
 fi
-CNODE_HOME=/opt/cardano/cnode
-CONFIG=$CNODE_HOME/files/config.json
-PROTOCOL=$(jq -r .Protocol "$CONFIG")
+
+[[ -z "${CNODE_HOME}" ]] && CNODE_HOME=/opt/cardano/cnode
+
+if [[ -z "${SOCKET}" ]]; then
+  if [[ "$(ps -ef | grep "[c]ardano-node.*.${CNODE_HOME}")" =~ --socket-path[[:space:]]([^[:space:]]+) ]]; then
+    export CARDANO_NODE_SOCKET_PATH="${BASH_REMATCH[1]}"
+  else
+    echo "Node socket not set in env file and automatic detection failed!"
+    return 1
+  fi
+else
+  export CARDANO_NODE_SOCKET_PATH="${SOCKET}"
+fi
+
+if [[ -z "${CONFIG}" ]]; then
+  if [[ "$(ps -ef | grep "[c]ardano-node.*.${CNODE_HOME}")" =~ --config[[:space:]]([^[:space:]]+) ]]; then
+    CONFIG=${BASH_REMATCH[1]}
+  else
+    echo "Node config not set in env file and automatic detection failed!"
+    return 1
+  fi
+fi
+
+if [[ -z "${TOPOLOGY}" ]]; then
+  if [[ "$(ps -ef | grep "[c]ardano-node.*.${CNODE_HOME}")" =~ --topology[[:space:]]([^[:space:]]+) ]]; then
+    TOPOLOGY=${BASH_REMATCH[1]}
+  else
+    echo "Node topology not set in env file and automatic detection failed!"
+    return 1
+  fi
+fi
+
+if [[ ${EKG_HOST} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+  OIFS=$IFS
+  IFS='.'
+  EKG_OCTETS=(${EKG_HOST})
+  IFS=$OIFS
+  if ! [[ ${EKG_OCTETS[0]} -le 255 && ${EKG_OCTETS[1]} -le 255 && ${EKG_OCTETS[2]} -le 255 && ${EKG_OCTETS[3]} -le 255 ]]; then
+    echo "Not a valid IP range set for EKG host, please check env file!"
+    return 1
+  fi
+else
+  echo "Not a valid IP format set for EKG host, please check env file!"
+  return 1
+fi
+
+if [[ -z ${EKG_PORT} ]]; then
+  if ! EKG_PORT=$(jq -er '.hasEKG' "${CONFIG}" 2>/dev/null); then
+    echo "Could not get 'hasEKG' port from the node configuration file"
+    return 1
+  fi
+elif [[ ! ${EKG_PORT} =~ ^[0-9]+$ ]]; then
+  echo "Please set a valid EKG port number in env file!"
+  return 1
+fi
+
+if ! GENESIS_JSON=$(jq -er '.ShelleyGenesisFile' "${CONFIG}" 2>/dev/null); then
+  echo "Could not get 'ShelleyGenesisFile' from the node configuration file"
+  return 1
+else
+  # if relative path is used, assume same parent dir as config
+  [[ ! ${GENESIS_JSON} =~ ^/ ]] && GENESIS_JSON="$(dirname "${CONFIG}")/${GENESIS_JSON}"
+  [[ ! -f "${GENESIS_JSON}" ]] && echo "Shelley genesis file not found: ${GENESIS_JSON}" && return 1
+fi
+
+if ! BYRON_GENESIS_JSON=$(jq -er '.ByronGenesisFile' "${CONFIG}" 2>/dev/null); then
+  echo "Could not get 'ByronGenesisFile' from the node configuration file"
+  return 1
+else
+  # if relative path is used, assume same parent dir as config
+  [[ ! ${BYRON_GENESIS_JSON} =~ ^/ ]] && BYRON_GENESIS_JSON="$(dirname "${CONFIG}")/${BYRON_GENESIS_JSON}"
+  [[ ! -f "${BYRON_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${BYRON_GENESIS_JSON}" && return 1
+fi
+
+CNODE_PID=$(ps -ef | grep "[-]-port ${CNODE_PORT}" | awk '{print $2}')
+
+PROTOCOL=$(jq -r .Protocol "${CONFIG}")
+NETWORKID=$(jq -r .networkId ${GENESIS_JSON})
+MAGIC=$(jq -r .protocolMagicId < ${GENESIS_JSON})
+NWMAGIC=$(jq -r .networkMagic < ${GENESIS_JSON})
 [[ "${PROTOCOL}" = "Cardano" ]] && PROTOCOL_IDENTIFIER="--cardano-mode" || PROTOCOL_IDENTIFIER="--shelley-mode"
-GENESIS_JSON=$CNODE_HOME/files/genesis.json
-NETWORKID=$(jq -r .networkId $GENESIS_JSON)
-BYRON_GENESIS_JSON=$CNODE_HOME/files/byron-genesis.json
-export CARDANO_NODE_SOCKET_PATH=$CNODE_HOME/sockets/node0.socket
-MAGIC=$(jq -r .protocolMagicId < $GENESIS_JSON)
-NWMAGIC=$(jq -r .networkMagic < $GENESIS_JSON)
-[[ "${NETWORKID}" = "Mainnet" ]] && HASH_IDENTIFIER="--mainnet" || HASH_IDENTIFIER="--testnet-magic ${NWMAGIC}"
-[[ "${NWMAGIC}" = "764824073" ]] && NETWORK_IDENTIFIER="--mainnet" || NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}"
+if [[ "${NWMAGIC}" = "764824073" ]]; then
+  NETWORK_IDENTIFIER="--mainnet"
+  NETWORK_NAME="Mainnet"
+else
+  NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}"
+  [[ "${NWMAGIC}" = "1097911063" ]] && NETWORK_NAME="Testnet" || NETWORK_NAME="Custom"
+fi
+
+PROT_PARAMS="$(${CCLI} shelley query protocol-parameters ${PROTOCOL_IDENTIFIER} ${NETWORK_IDENTIFIER} 2>&1)"
+if [[ -n "${PROT_PARAMS}" ]] && ! DECENTRALISATION=$(jq -er .decentralisationParam <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
+
+SHELLEY_GENESIS_START_SEC=$(date --date="$(jq -r .systemStart "${GENESIS_JSON}")" +%s)
+EPOCH_LENGTH=$(jq -r .epochLength "${GENESIS_JSON}")
+SLOT_LENGTH=$(jq -r .slotLength "${GENESIS_JSON}")
+ACTIVE_SLOTS_COEFF=$(jq -r .activeSlotsCoeff "${GENESIS_JSON}")
+SLOTS_PER_KES_PERIOD=$(jq -r .slotsPerKESPeriod "${GENESIS_JSON}")
+MAX_KES_EVOLUTIONS=$(jq -r .maxKESEvolutions "${GENESIS_JSON}")
+if [[ "${PROTOCOL_IDENTIFIER}" = "--cardano-mode" ]]; then
+  BYRON_GENESIS_START_SEC=$(jq -r .startTime "${BYRON_GENESIS_JSON}")
+  BYRON_K=$(jq -r .protocolConsts.k "${BYRON_GENESIS_JSON}")
+  BYRON_SLOT_LENGTH=$(( $(jq -r .blockVersionData.slotDuration "${BYRON_GENESIS_JSON}") / 1000 ))
+  BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
+fi
+
+FG_BLACK=$(tput setaf 0)
+FG_RED=$(tput setaf 1)
+FG_GREEN=$(tput setaf 2)
+FG_YELLOW=$(tput setaf 3)
+FG_BLUE=$(tput setaf 4)
+FG_MAGENTA=$(tput setaf 5)
+FG_CYAN=$(tput setaf 6)
+FG_WHITE=$(tput setaf 7)
+STANDOUT=$(tput smso)
+BOLD=$(tput bold)
+NC=$(tput sgr0)
+
+[[ -z ${BLOCK_LOG_DIR} && -d "${CNODE_HOME}/db/blocks" ]] && BLOCK_LOG_DIR="${CNODE_HOME}/db/blocks"
+
+return 0
