Node 8.7.3 (#1725)
## Description
Breaking updates due to node 8.7.3 release.
Initial commit, untested and most likely incomplete. 

- [x]  Docs update
- [x] Test all touched scripts

---------

Co-authored-by: Greg Beresnev <greg.beresnev@yarris.com>
Co-authored-by: rdlrt <3169068+rdlrt@users.noreply.github.com>

diff --git a/scripts/cnode-helper-scripts/env b/scripts/cnode-helper-scripts/env
--- a/scripts/cnode-helper-scripts/env
+++ b/scripts/cnode-helper-scripts/env
@@ -78,9 +78,12 @@
 #ASSET_POLICY_SK_FILENAME="policy.skey"
 #ASSET_POLICY_SCRIPT_FILENAME="policy.script"           # File extension '.script' mandatory
 #ASSET_POLICY_ID_FILENAME="policy.id"
+
 #CIP0094_POLL_URL="https://raw.githubusercontent.com/cardano-foundation/CIP-0094-polls/main/networks/polls.json" # URL for polls to vote against
 
-#MITHRIL_DOWNLOAD="N"                                  # (Y|N) Download latest Mithril snapshot
+#MITHRIL_DOWNLOAD="N"                                   # (Y|N) Download latest Mithril snapshot
+
+#STRICT_VERSION_CHECK="Y"                               # (Y|N) Restrict operation to supported major.minor version leaving patch version open. If disabled, any version will be accepted (unsupported)
 
 ######################################
 # Do NOT modify code below           #
@@ -102,10 +105,12 @@ is_dir() {
 
 # Description : Check higher of two versions
 #             : $1=minimal_needed_version
-#             : $2=current_node_version
-versionCheck()
-{
-  printf '%s\n%s' "${1//v/}" "${2//v/}" | sort -C -V
+#             : $2=current_version
+versionCheck() {
+  [[ ${STRICT_VERSION_CHECK} = N ]] && return 0
+  w_ver=${1//v/}; w_ver_dots=${w_ver//[^.]}; [[ ${#w_ver_dots} -gt 1 && ${w_ver} =~ ^([0-9]+.[0-9]) ]] && w_ver=${BASH_REMATCH[1]}
+  c_ver=${2//v/}; c_ver_dots=${c_ver//[^.]}; [[ ${#c_ver_dots} -gt 1 && ${c_ver} =~ ^([0-9]+.[0-9]) ]] && c_ver=${BASH_REMATCH[1]}
+  printf '%s\n%s' "${w_ver}" "${c_ver}" | sort -C -V
 }
 
 # Description : Exit with error message
@@ -443,6 +448,7 @@ getPassword() {
     fi
   done
 }
+
 readPassword() {
   read_password=""
   prompt="$1: "
@@ -567,7 +573,7 @@ getNodeMetrics() {
     [[ ${node_metrics} =~ cardano_node_metrics_RTS_gcMajorNum_int[[:space:]]([^[:space:]]*) ]] && gc_major=${BASH_REMATCH[1]} || gc_major=0
     [[ ${node_metrics} =~ cardano_node_metrics_forks_int[[:space:]]([^[:space:]]*) ]] && forks=${BASH_REMATCH[1]} || forks=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_s[[:space:]]([^[:space:]]*) ]] && block_delay=${BASH_REMATCH[1]} || block_delay=0
-    [[ ${node_metrics} =~ cardano_node_metrics_served_block_count_int[[:space:]]([^[:space:]]*) ]] && blocks_served=${BASH_REMATCH[1]} || block_served=0
+    [[ ${node_metrics} =~ cardano_node_metrics_served_block_count_int[[:space:]]([^[:space:]]*) ]] && blocks_served=${BASH_REMATCH[1]} || blocks_served=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_lateblocks[[:space:]]([^[:space:]]*) ]] && blocks_late=${BASH_REMATCH[1]} || blocks_late=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_cdfOne[[:space:]]([^[:space:]]*) ]] && printf -v blocks_w1s "%.6f" ${BASH_REMATCH[1]} || blocks_w1s=0
     [[ ${node_metrics} =~ cardano_node_metrics_blockfetchclient_blockdelay_cdfThree[[:space:]]([^[:space:]]*) ]] && printf -v blocks_w3s "%.6f" ${BASH_REMATCH[1]} || blocks_w3s=0
@@ -726,10 +732,10 @@ getPoolID() {
   pool_id_bech32=""
   pool_coldkey_vk_file="${pool_dir}/${POOL_COLDKEY_VK_FILENAME}"
   if [[ -f ${pool_coldkey_vk_file} ]]; then
-    println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file} --output-format hex"
-    println ACTION "${CCLI} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file}"
-    if ! pool_id=$(${CCLI} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" --output-format hex 2>/dev/null) || \
-       ! pool_id_bech32=$(${CCLI} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" 2>/dev/null); then
+    [[ $(type -t println) = function ]] && println ACTION "${CCLI} ${NETWORK_ERA} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file} --output-format hex"
+    [[ $(type -t println) = function ]] && println ACTION "${CCLI} ${NETWORK_ERA} stake-pool id --cold-verification-key-file ${pool_coldkey_vk_file}"
+    if ! pool_id=$(${CCLI} ${NETWORK_ERA} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" --output-format hex 2>/dev/null) || \
+       ! pool_id_bech32=$(${CCLI} ${NETWORK_ERA} stake-pool id --cold-verification-key-file "${pool_coldkey_vk_file}" 2>/dev/null); then
       return 1
     fi
     echo ${pool_id} > "${pool_id_file}"
@@ -741,25 +747,16 @@ getPoolID() {
 
 # Description : Calculate expected interval between blocks
 slotInterval() {
-  if [[ -z ${DECENTRALISATION} || $(echo "${DECENTRALISATION} < 0.5" | bc) -eq 1 ]]; then d=0.5; else d=${DECENTRALISATION}; fi
-  echo "(${SLOT_LENGTH} / ${ACTIVE_SLOTS_COEFF} / ${d}) + 0.5" | bc -l | awk '{printf "%.0f\n", $1}'
+  echo "(${SLOT_LENGTH} / ${ACTIVE_SLOTS_COEFF}) + 0.5" | bc -l | awk '{printf "%.0f\n", $1}'
 }
 
-# Description : Identify current era and set variables accordingly
-# TODO: Track progress of https://github.com/intersectmbo/cardano-node/pull/4135 to see if era identifier can be removed in a future release. 
-getEraIdentifier() {
-  NETWORK_ERA=$(${CCLI} query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty')
-  case ${NETWORK_ERA} in
-    Byron)   ERA_IDENTIFIER="--byron-era" ;;
-    Shelley) ERA_IDENTIFIER="--shelley-era" ;;
-    Allegra) ERA_IDENTIFIER="--allegra-era" ;;
-    Mary)    ERA_IDENTIFIER="--mary-era" ;;
-    Alonzo)  ERA_IDENTIFIER="--alonzo-era" ;;
-    Babbage) ERA_IDENTIFIER="--babbage-era" ;;
-    *)       ERA_IDENTIFIER="--babbage-era"
-             [[ ${OFFLINE_MODE} = "N" ]] && return 1
-  esac
-  return 0
+getProtocolParams() {
+  PROT_PARAMS="$(${CCLI} ${NETWORK_ERA} query protocol-parameters ${NETWORK_IDENTIFIER} 2>/dev/null)"
+  read -ra PROT_PARAMS_VERSION <<<"$(jq -r '[ .protocolVersion.major //0, .protocolVersion.minor //0]| @tsv' <<<"${PROT_PARAMS}" 2>/dev/null)"
+  PROT_MAJOR=${PROT_PARAMS_VERSION[0]}
+  PROT_MINOR=${PROT_PARAMS_VERSION[1]}
+  PROT_VERSION="${PROT_MAJOR}.${PROT_MINOR}"
+  [[ ${PROT_MAJOR} -eq 0 ]] && return 1 || return 0
 }
 
 telegramSend() {
@@ -840,6 +837,7 @@ set_default_vars() {
   [[ -z ${ASSET_POLICY_ID_FILENAME} ]] && ASSET_POLICY_ID_FILENAME="policy.id"
   [[ -z ${CIP0094_POLL_URL} ]] && CIP0094_POLL_URL="https://raw.githubusercontent.com/cardano-foundation/CIP-0094-polls/main/networks/polls.json"
   [[ -z ${MITHRIL_DOWNLOAD} ]] && MITHRIL_DOWNLOAD="N"
+  [[ -z ${STRICT_VERSION_CHECK} ]] && STRICT_VERSION_CHECK="Y"
   FG_BLACK='\e[30m'
   FG_RED='\e[31m'
   FG_GREEN='\e[32m'
@@ -854,6 +852,27 @@ set_default_vars() {
   STANDOUT='\e[7m'
   BOLD='\e[1m'
   NC='\e[0m'
+}
+
+read_genesis() {
+  read -ra SHGENESIS <<< "$(jq -r '[ .networkMagic, .systemStart, .epochLength, .slotLength, .activeSlotsCoeff, .slotsPerKESPeriod, .maxKESEvolutions ] |@tsv' < ${GENESIS_JSON})"
+  read -ra BYGENESIS <<< "$(jq -r '[ .startTime, .protocolConsts.k, .blockVersionData.slotDuration ] |@tsv' < ${BYRON_GENESIS_JSON})"
+  NWMAGIC=${SHGENESIS[0]}
+  SHELLEY_GENESIS_START_SEC=$(date --date="${SHGENESIS[1]}" +%s)
+  EPOCH_LENGTH=${SHGENESIS[2]}
+  SLOT_LENGTH=${SHGENESIS[3]}
+  ACTIVE_SLOTS_COEFF=${SHGENESIS[4]}
+  SLOTS_PER_KES_PERIOD=${SHGENESIS[5]}
+  MAX_KES_EVOLUTIONS=${SHGENESIS[6]}
+  BYRON_GENESIS_START_SEC=${BYGENESIS[0]}
+  BYRON_K=${BYGENESIS[1]}
+  BYRON_SLOT_LENGTH=${BYGENESIS[2]}
+  BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
+}
+
+test_koios() {
+  # make sure KOIOS_API is reachable, else fall back to cli
+  [[ ${ENABLE_KOIOS} = 'Y' && -n ${KOIOS_API} && $(curl -sfk -o /dev/null -w "%{http_code}" -m 5 ${KOIOS_API}/tip | awk '{print $1}') = "200" ]] || unset KOIOS_API
 }
 
 [[ ${0} != '-bash' ]] && PARENT=$(dirname $0) || PARENT="$(pwd)" # If sourcing at terminal, $0 would be "-bash" , which is invalid. Thus, fallback to present working directory
@@ -890,6 +909,13 @@ fi
 
 if [[ -z "${CNCLI}" ]]; then
   CNCLI=$(command -v cncli) || CNCLI="${HOME}/.local/bin/cncli"
+fi
+
+node_version="$(${CNODEBIN} version | head -1 | cut -d' ' -f2)"
+cli_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
+if ! versionCheck "8.7.3" "${node_version}" || ! versionCheck "8.17.0.0" "${cli_version}"; then
+  echo -e "\nKoios scripts have now been upgraded to support cardano-node 8.7.x ('${node_version}' found) / cardano-cli 8.17.x.x ('${cli_version}' found).\nPlease update cardano-node binaries (ensure to read release notes and update various configs using guild-deploy (use appropriate options to download/install/overwrite parts you need) or use tagged branches for older node version (eg: ./<script>.sh -b node-8.1.2 to switch scripts to an older branch).\n\n"
+  return 1
 fi
 
 [[ -f /usr/local/lib/libsodium.so ]] && export LD_LIBRARY_PATH=/usr/local/lib:"${LD_LIBRARY_PATH}" && PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:"${PKG_CONFIG_PATH}"
@@ -933,6 +959,9 @@ if ! command -v "jq" &>/dev/null; then
   return 1
 fi
 
+NETWORK_ERA=$(${CCLI} latest query tip ${NETWORK_IDENTIFIER} 2>/dev/null | jq -r '.era //empty' | tr '[:upper:]' '[:lower:]')
+[[ -z ${NETWORK_ERA} ]] && NETWORK_ERA=latest
+
 read -ra CONFIG_CONTENTS <<<"$(jq -r '[ .AlonzoGenesisFile //"null", .ByronGenesisFile //"null", .ShelleyGenesisFile //"null", .Protocol //"Cardano", .TraceChainDb //"null", .EnableP2P //"false", .ConwayGenesisFile //"null"]| @tsv' "${CONFIG}" 2>/dev/null)"
 if [[ ${CONFIG_CONTENTS[4]} != "true" ]]; then
   echo "Could not find TraceChainDb when attempting to parse ${CONFIG} file in JSON format, please double-check the syntax of your config, or simply download it from guild-operators repository!"
@@ -952,7 +981,7 @@ else
   [[ ! -f "${ALONZO_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${ALONZO_GENESIS_JSON}" && return 1
   [[ ! -f "${BYRON_GENESIS_JSON}" ]] && echo "Byron genesis file not found: ${BYRON_GENESIS_JSON}" && return 1
   [[ ! -f "${GENESIS_JSON}" ]] && echo "Shelley genesis file not found: ${GENESIS_JSON}" && return 1
-  GENESIS_HASH="$(${CCLI} genesis hash --genesis "${GENESIS_JSON}")"
+  GENESIS_HASH="$(${CCLI} ${NETWORK_ERA} genesis hash --genesis "${GENESIS_JSON}")"
   PROTOCOL="${CONFIG_CONTENTS[3]}"
   P2P_ENABLED="${CONFIG_CONTENTS[5]}"
 fi
@@ -1029,28 +1058,6 @@ if [[ -n "${CNODE_PID}" ]]; then
   fi
 fi
 
-node_version="$(${CCLI} version | head -1 | cut -d' ' -f2)"
-if ! versionCheck "8.1.2" "${node_version}"; then
-  echo -e "\nKoios scripts has now been upgraded to support cardano-node 8.1.2 or higher (${node_version} found).\nPlease update cardano-node (note that you should ideally update your config too) or use tagged branches for older node version (eg: ./<script>.sh -b node-1.35.7 to switch scripts to an older branch).\n\n"
-  return 1
-fi
-
-read_genesis() {
-  read -ra SHGENESIS <<< "$(jq -r '[ .networkMagic, .systemStart, .epochLength, .slotLength, .activeSlotsCoeff, .slotsPerKESPeriod, .maxKESEvolutions ] |@tsv' < ${GENESIS_JSON})"
-  read -ra BYGENESIS <<< "$(jq -r '[ .startTime, .protocolConsts.k, .blockVersionData.slotDuration ] |@tsv' < ${BYRON_GENESIS_JSON})"
-  NWMAGIC=${SHGENESIS[0]}
-  SHELLEY_GENESIS_START_SEC=$(date --date="${SHGENESIS[1]}" +%s)
-  EPOCH_LENGTH=${SHGENESIS[2]}
-  SLOT_LENGTH=${SHGENESIS[3]}
-  ACTIVE_SLOTS_COEFF=${SHGENESIS[4]}
-  SLOTS_PER_KES_PERIOD=${SHGENESIS[5]}
-  MAX_KES_EVOLUTIONS=${SHGENESIS[6]}
-  BYRON_GENESIS_START_SEC=${BYGENESIS[0]}
-  BYRON_K=${BYGENESIS[1]}
-  BYRON_SLOT_LENGTH=${BYGENESIS[2]}
-  BYRON_EPOCH_LENGTH=$(( 10 * BYRON_K ))
-}
-
 read_genesis
 
 [[ ${NWMAGIC} == "764824073" ]] && NETWORK_IDENTIFIER="--mainnet" || NETWORK_IDENTIFIER="--testnet-magic ${NWMAGIC}"
@@ -1079,11 +1086,6 @@ case ${NWMAGIC} in
     [[ -z ${SHELLEY_TRANS_EPOCH} ]] && SHELLEY_TRANS_EPOCH=0
 esac
 
-test_koios() {
-  # make sure KOIOS_API is reachable, else fall back to cli
-  [[ ${ENABLE_KOIOS} = 'Y' && -n ${KOIOS_API} && $(curl -sfk -o /dev/null -w "%{http_code}" -m 5 ${KOIOS_API}/tip | awk '{print $1}') = "200" ]] || unset KOIOS_API
-}
-
 [[ ${OFFLINE_MODE} = "N" && ${SHELLEY_TRANS_EPOCH} -eq -1 ]] && getNodeMetrics && getShelleyTransitionEpoch
 
 # Return code 2 is used for scripts that want to source env but not fail due to a starting node
@@ -1095,8 +1097,9 @@ if [[ ${OFFLINE_MODE} = "N" && ! -S ${CARDANO_NODE_SOCKET_PATH} ]]; then
   return 2
 fi
 
-if [[ ${OFFLINE_MODE} = "N" ]] && ! PROT_PARAMS="$(${CCLI} query protocol-parameters ${NETWORK_IDENTIFIER} 2>&1)"; then echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}" && return 2; fi
-
-if ! DECENTRALISATION=$(jq -er .decentralization <<< ${PROT_PARAMS} 2>/dev/null); then DECENTRALISATION=0.5; fi
+if [[ ${OFFLINE_MODE} = "N" ]] && ! getProtocolParams; then
+  echo -e "${FG_RED}Failed to query protocol-parameters from node, not yet fully started?${NC}"
+  return 2
+fi
 
 return 0
